Host __REMOTE_ALIAS__
    HostName __REMOTE_HOSTNAME__
    User __REMOTE_USER__
    IdentityFile __REMOTE_SSH_KEY__
    ServerAliveInterval 30
    ServerAliveCountMax 3
    ControlMaster auto
    ControlPath ~/.ssh/sockets/__REMOTE_ALIAS__-%r@%h:%p
    ControlPersist 30m
