Host ax41
    HostName __AX41_HOST__
    User __AX41_USER__
    IdentityFile __AX41_SSH_KEY__
    ServerAliveInterval 30
    ServerAliveCountMax 3
    ControlMaster auto
    ControlPath ~/.ssh/sockets/ax41-%r@%h:%p
    ControlPersist 30m
